version: '3'

services:
  redis:
    image: redis:latest
    expose:
      - 6379
    command: redis-server

  db:
    image: postgres:latest
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jheep_db
    volumes:
      - jheep_db:/var/lib/postgresql/data:rw

  server:
    image: ${DOCKER_REGISTRY}/jheep-server:latest
    build:
      context: ${JHEEP_PATH}/backend
      dockerfile: .docker/Dockerfile.server
      args:
        - GIT_REF=${GIT_REF}
        - APP_DIR=${JHEEP_BACK_DIR}
    volumes:
      - ${JHEEP_PATH}/backend:${JHEEP_BACK_DIR}:rw
      - ${JHEEP_PATH}/examples:${JHEEP_EXAMPLES_DIR}:rw
      - jheep_data:${JHEEP_CONFIG_DIR}:rw
    ports:
      - 8801:8801
    environment:
      - JHEEP_PATH=${JHEEP_BACK_DIR}
      - JHEEP_CONFIG_PATH=${JHEEP_CONFIG_DIR}
      - JHEEP_EXAMPLES_PATH=${JHEEP_EXAMPLES_DIR}
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=jheep_db
      - ENVIRONMENT=development
    working_dir: ${JHEEP_BACK_DIR}
    depends_on:
      - db
      - redis

volumes:
  jheep_db:
    driver: local
  jheep_data:
    driver: local
