version: '3'

services:
  memcached:
    image: memcached:latest
    expose:
      - 11211
    command: ["-m", "8096"]

  db:
    image: postgres:latest
    #expose:
    #  - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jheep_db
    volumes:
      - jheep_db:/var/lib/postgresql/data:rw

  redis:
    image: redis:latest
    expose:
      - 6379
    command: redis-server

  server:
    image: ${DOCKER_REGISTRY}/jheep-server:latest
    build:
      context: ${JHEEP_PATH}/backend
      dockerfile: .docker/Dockerfile.server
      args:
        - GIT_REF=${GIT_REF}
        - APP_DIR=${BACK_APP_DIR}
    volumes:
      - ${JHEEP_PATH}/backend:${BACK_APP_DIR}:rw
      - ${JHEEP_PATH}/examples:/examples:rw
      - jheep_data:/examples/.data
    ports:
      - 8801:8801
    environment:
      - JHEEP_PATH=${BACK_APP_DIR}
      - JHEEP_EXAMPLES_PATH=/examples
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=jheep_db
      - ENVIRONMENT=development
    working_dir: ${BACK_APP_DIR}
    depends_on:
      - db
      - memcached
      - redis

  worker:
    image: ${DOCKER_REGISTRY}/jheep-worker:latest
    build:
      context: ${JHEEP_PATH}/backend
      dockerfile: .docker/Dockerfile.worker
      args:
        - GIT_REF=${GIT_REF}
        - USERNAME=${DOCKER_USER}
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - APP_DIR=${BACK_APP_DIR}
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          device_ids: ['0', '1']
    #          capabilities: [gpu]
    #ipc: host
    #shm_size: 2048M
    user: ${USERID}:${GROUPID}
    volumes:
      - ${JHEEP_PATH}/backend:${BACK_APP_DIR}:rw
      - ${JHEEP_PATH}/examples:/examples:rw
      - jheep_data:/examples/.data
    ports:
      - 8899:8899
    environment:
      - JHEEP_PATH=${BACK_APP_DIR}
      - JHEEP_EXAMPLES_PATH=/examples
      #- NVIDIA_DRIVER_CAPABILITIES=all
      #- NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_PORT=8899
    working_dir: ${BACK_APP_DIR}
    depends_on:
      - server
        
#  gpu-worker:
#    image: ${DOCKER_REGISTRY}/jheep-cpu-worker:latest
#    build:
#      context: ${JHEEP_PATH}/backend
#      dockerfile: .docker/Dockerfile.cpu-worker
#      args:
#        - GIT_REF=${GIT_REF}
#        - USERNAME=${DOCKER_USER}
#        - USERID=${USERID}
#        - GROUPID=${GROUPID}
#        - APP_DIR=${BACK_APP_DIR}
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: ['0', '1']
#              capabilities: [gpu]
#    ipc: host
#    shm_size: 2048M
#    user: ${USERID}:${GROUPID}
#    volumes:
#      - ${JHEEP_PATH}/backend:${BACK_APP_DIR}:rw
#      - ${JHEEP_PATH}/examples:/examples:rw
#      - jheep_data:/examples/.data
#    ports:
#      - 8899:8899
#    environment:
#      - JHEEP_PATH=${BACK_APP_DIR}
#      - JHEEP_EXAMPLES_PATH=/examples
#      #- NVIDIA_DRIVER_CAPABILITIES=all
#      #- NVIDIA_VISIBLE_DEVICES=all
#      - JUPYTER_PORT=8899
#    working_dir: ${BACK_APP_DIR}
#    depends_on:
#      - server
#      - scheduler
        
volumes:
  jheep_db:
    driver: local
  jheep_data:
    driver: local
