version: '3'

services:
  worker:
    image: ${DOCKER_REGISTRY}/jheep-worker:latest
    build:
      context: ${JHEEP_PATH}/backend
      dockerfile: .docker/Dockerfile.worker
      args:
        - GIT_REF=${GIT_REF}
        - USERNAME=${DOCKER_USER}
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - APP_DIR=${JHEEP_BACK_DIR}
        - EX_DIR=${JHEEP_EXAMPLES_DIR}
    user: ${USERID}:${GROUPID}
    volumes:
      - ${JHEEP_PATH}/backend:${JHEEP_BACK_DIR}:rw
      - ${JHEEP_PATH}/examples:${JHEEP_EXAMPLES_DIR}:rw
      - jheep_data:${JHEEP_CONFIG_DIR}:rw
    ports:
      - 8787:8787
      - 8899:8899
    environment:
      - JHEEP_PATH=${JHEEP_BACK_DIR}
      - JHEEP_CONFIG_PATH=${JHEEP_CONFIG_DIR}
      - JHEEP_EXAMPLES_PATH=${JHEEP_EXAMPLES_DIR}
      - JUPYTER_PORT=8899
    working_dir: ${JHEEP_BACK_DIR}
        
#  gpu-worker:
#    image: ${DOCKER_REGISTRY}/jheep-cpu-worker:latest
#    build:
#      context: ${JHEEP_PATH}/backend
#      dockerfile: .docker/Dockerfile.cpu-worker
#      args:
#        - GIT_REF=${GIT_REF}
#        - USERNAME=${DOCKER_USER}
#        - USERID=${USERID}
#        - GROUPID=${GROUPID}
#        - APP_DIR=${JHEEP_BACK_DIR}
#        - EX_DIR=${JHEEP_EXAMPLES_DIR}
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: ['0', '1']
#              capabilities: [gpu]
#    ipc: host
#    shm_size: 2048M
#    user: ${USERID}:${GROUPID}
#    volumes:
#      - ${JHEEP_PATH}/backend:${JHEEP_BACK_DIR}:rw
#      - ${JHEEP_PATH}/examples:${JHEEP_EXAMPLES_DIR}:rw
#      - jheep_data:${JHEEP_CONFIG_DIR}:rw
#    ports:
#      - 8899:8899
#    environment:
#      - JHEEP_PATH=${JHEEP_BACK_DIR}
#      - JHEEP_CONFIG_PATH=${JHEEP_CONFIG_DIR}
#      - JHEEP_EXAMPLES_PATH=${JHEEP_EXAMPLES_DIR}
#      #- NVIDIA_DRIVER_CAPABILITIES=all
#      #- NVIDIA_VISIBLE_DEVICES=all
#      - JUPYTER_PORT=8899
#    working_dir: ${JHEEP_BACK_DIR}

volumes:
  jheep_db:
    driver: local
  jheep_data:
    driver: local
